---
title: "HW_Week5"
author: "Vitaly Briker"
date: "June 11, 2018"
output: html_document
---

## Problem Description
Backstory: Your client is expecting a baby soon.  However, he is not sure what to name the child.  Being out of the loop, he hires you to help him figure out popular names.  He provides for you raw data in order to help you make a decision.

## Answer Question 1 (a,b,c,d)

```{r names}
setwd("F:\\My_Docs\\univer\\DataScience\\git\\Home_Work5\\HW5")
df = read.delim("yob2016.txt",header = FALSE,sep = ";",col.names=c("Name","Gender","Amount"))
head(df)
summary(df)
str(df)
find_abn=df$Name[grep(".*yyy.*",df$Name)]
find_abn
y2016 =df[!rownames(df) %in% grep(".*yyy.*",df$Name),]
```

## Answer Question 2 (a,b,c)

```{r names1}
y2015 = read.delim("yob2015.txt",header = FALSE,sep = ",",col.names=c("Name","Gender","Amount"))
head(y2015)
summary(y2015)
str(y2015)
tail(y2015,10)

final=merge(y2015,y2016,by="Name")
```

## Answer Question 3 (a,b,c,d)

```{r name2}
final$Total=final$Amount.x+final$Amount.y
nrow(final)


final=final[order(final$Total),]
TOP10_Popular_names=tail(final,10)
TOP10_Popular_names


female_names=subset(final, Gender.x=="F" | Gender.y=="F")
Popular_girls_names=tail(female_names[order(female_names$Total),],10)   
Popular_girls_names

par(las=2)
barplot(Popular_girls_names$Total,names.arg=Popular_girls_names$Name,
        main = "TOP10 Most Popular Girls Names 2015-2016",
        horiz=FALSE,col='darkblue')

write.csv(subset(Popular_girls_names, select=c("Name","Total")),file = "Popular_Girls_Names_2015-2016.csv",row.names = FALSE)
```


## GitHub Link
https://github.com/vbriker/HW5
